apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  .sandbox_metadata.yaml: |
    host: "0.0.0.0"
    port: 8080
    log_level: info
    auto_reload: false
    workers: 1
    db_url: mongodb://localhost:27017
    db_name: metadata
    cors_allowed_origins: ["*"]
    cors_allow_credentials: true
    cors_allowed_methods: ["*"]
    cors_allowed_headers: ["*"]
