replicaCount: 3
postgresql:
  global: 
    storageClass: csi-cinder-sc-retain
    imagePullSecrets:
    - dockerhub
  postgresqlDatabase: storage
  postgresqlUsername: admin
  postgresqlPassword: admin
pgweb:
  imagePullSecrets: ["dockerhub"]
  env:
  - DATABASE_URL=postgres://admin:admin@sandbox-storage-postgres:5432/storage?sslmode=disable
