replicaCount: 3
postgresql:
  global: 
    storageClass: csi-cinder-sc-retain
    imagePullSecrets:
    - dockerhub
  postgresqlDatabase: storage
  postgresqlUsername: admin
  postgresqlPassword: admin
pgweb:
  imagePullSecrets:
  - name: dockerhub
  env:
  - name: DATABASE_URL
    value: postgres://admin:admin@sandbox-storage-postgresql:5432/storage?sslmode=disable
