apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  .sandbox_storage.yaml: |
    host: "0.0.0.0"
    port: 8080
    log_level: info
    drs_path: drs://localhost:8080/
    api_path: /ga4gh/drs/v1
    custom_spec_url: https://sandbox.api.ghga-dev.de/storage/ga4gh/drs/v1/openapi.yaml
    cors_allowed_origins: ["*"]
    cors_allow_credentials: true
    cors_allowed_methods: ["*"]
    cors_allowed_headers: ["*"]
    db_path: postgresql://admin:admin@sandbox-storage-postgresql:5432/storage?sslmode=disable