apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    category: test
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}
