apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
data:
  .sandbox_ui.yaml: |
    host: "0.0.0.0"
    port: 8080
    welcome_info: |
      This web app is part of an implementation study.
      It only contains basic functionalities and shouldn't be used
      for production.
    svc_metadata_url: "https://sandbox.api.ghga-dev.de/metadata"
    svc_storage_url: "https://sandbox.api.ghga-dev.de/storage"
    svc_request_url: "https://sandbox.api.ghga-dev.de/request"
