apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: sandbox-ca-issuer
  name: argocd
  namespace: foundation
spec:
  rules:
  - host: argo.ghga-dev.de
    http:
      paths:
      - backend:
          serviceName: argo-cd-argocd-server
          servicePort: 80
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - argo.ghga-dev.de
    secretName: mongo-request-tlsargocd-tls
