apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: sandbox-ca-issuer
    kubernetes.io/ingress.class: nginx
  name: rabbitmq-dashboard
  namespace: foundation
spec:
  rules:
  - host: rabbitmq-dashboard.ghga-dev.de
    http:
      paths:
      - backend:
          serviceName: ghga-rabbitmq
          servicePort: 15672
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - rabbitmq-dashboard.ghga-dev.de
    secretName: mongo-request-tlsrabbitmq-dashboard-tls
