apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ghga-dev-internal
spec:
  secretName: ghga-dev-internal
  dnsNames:
  - "*.sandbox.svc.cluster.local"
  - "*.sandbox"
  - "*.ghga-dev.de"
  issuerRef:
    name: sandbox-ca-issuer