apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: sandbox-ca-issuer
  name: mongo-request
  namespace: sandbox
spec:
  rules:
  - host: mongo-request.ghga-dev.de
    http:
      paths:
      - backend:
          serviceName: {{ .Chart.Name }}-mongo-express
          servicePort: 8081
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - mongo-request.ghga-dev.de
  - secretName: mongo-request-tls
