name: Update Version Of Helm Chart
on:
  repository_dispatch: {}

  # Usage:
  # curl -X POST https://api.github.com/repos/<name_of_account>/<name_of_repo>/dispatches \
  #  -H 'Accept: application/vnd.github.everest-preview+json' \
  #  -u ${{ secrets.ACCESS_TOKEN }} \ # access token needs to be of format: <username>:<personal_access_token>
  #  --data '{"event_type": "new_chart_version", "client_payload": { "chart_name": "name_of_chart", "new_version": "new_version" }}'

jobs:
  updateVersion:
    if: github.event.action == 'new_chart_version'
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Replace appVersion in Chart.yaml
      run: |
        sed -i \
          's/^appVersion:.*$/appVersion: ${{ github.event.client_payload.new_version }}/' \
          './charts/${{ github.event.client_payload.chart_name }}/Chart.yaml'
          
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        message: 'update version of ${{ github.event.client_payload.chart_name }} to ${{ github.event.client_payload.new_version }}'
