name: Update App Version of A Helm Chart
on:
  repository_dispatch: {}

  # Usage:
  # curl -X POST https://api.github.com/repos/<name_of_account>/<name_of_repo>/dispatches \
  #  -H 'Accept: application/vnd.github.everest-preview+json' \
  #  -u ${{ secrets.ACCESS_TOKEN }} \ # access token needs to be of format: <username>:<personal_access_token>
  #  --data '{"event_type": "new_app_version", "client_payload": { "chart_name": "name_of_chart", "new_app_version": "new_app_version" }}'

jobs:
  updateVersion:
    if: github.event.action == 'new_app_version'
    runs-on: ubuntu-latest
    env:
      CHART_YAML: "./${{ github.event.client_payload.chart_name }}/Chart.yaml"
      NEW_APP_VERSION: "${{ github.event.client_payload.new_app_version }}"
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Replace appVersion in Chart.yaml
      run: |
        sed -i \
          "s/^appVersion:.*$/appVersion: \"${NEW_APP_VERSION}\"/" \
          "${CHART_YAML}"

    - name: Increment patch number of the chart version
      run: |
        MATCH_PATCH_REGEX='s/^\(version:\s[0-9]\.[0-9]\.\)\([0-9]*[^0-9]*\)$'

        # extract the current patch number from the Chart.yaml
        PATCH_NUMBER=$(
          cat "${CHART_YAML}" |\
          grep "version:" | \
          sed -n "${MATCH_PATCH_REGEX}/\2/p"
        )

        # bump the patch number
        PATCH_NUMBER_BUMPED=$((PATCH_NUMBER+1))

        # update the patch number in the Chart.yaml
        sed -i \
          "${MATCH_PATCH_REGEX}/\1${PATCH_NUMBER_BUMPED}/" \
          "${CHART_YAML}"
          
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        message: 'update app version of chart \"${{ github.event.client_payload.chart_name }}\" to ${{ github.event.client_payload.new_app_version }}'
